name: JD_share

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 2 20 1,10,20 * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_USER_ID: ${{ secrets.TG_USER_ID }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: 安装依赖包
              run: npm install
              
            - name: 运行云互助
              run: node JD-share.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt
